-- MySQL Script generated by MySQL Workbench
-- Jum 23 Nov 2018 05:27:49  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`book` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`book` (
  `bookid` VARCHAR(15) NOT NULL,
  `bookprice` INT NOT NULL,
  PRIMARY KEY (`bookid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bookstore`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookstore`;
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('VE0LqD085eMC', 139040);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('iQmPNDIAskUC', 115200);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('Aaug_RnI-xQC', 132600);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('0ENFDwAAQBAJ', 63750);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('iO5pApw2JycC', 230100);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('OyB4llvAoXQC', 144300);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('WV8pZj_oNBwC', 192400);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('LiWrXUHgnL8C', 82000);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('szF_pLGmJTQC', 52900);
INSERT INTO `bookstore`.`book` (`bookid`, `bookprice`) VALUES ('o-QCOFDHmPEC', 170100);

COMMIT;

